name: Brendan Goodenough
description: Full Stack Web Developer
meta_description: "My personal blog"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'https://goodenough.nz'
google_analytics: 'UA-96548595-1'
disqus: true
disqus_shortname: 'nerdenough'

# Details for the RSS feed generator
url:            'https://goodenough.nz'
author:         'Brendan Goodenough'
authorTwitter:  'nerdenough'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
